### ISSUE TITLE
issue: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by dylanninin** [dylanninin/vue-hackernews#12]
```javascript
Uncaught TypeError: Cannot read property 'path' of undefined
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1360:2), <anonymous>:32:21)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1318:2), <anonymous>:1358:13)
    at Array.forEach (native)
    at HTML5History.updateRoute (eval at <anonymous> (http://localhost:8080/app.js:1318:2), <anonymous>:1357:26)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1318:2), <anonymous>:1287:12)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1318:2), <anonymous>:1344:9)
    at step (eval at <anonymous> (http://localhost:8080/app.js:1318:2), <anonymous>:1253:7)
    at step (eval at <anonymous> (http://localhost:8080/app.js:1318:2), <anonymous>:1260:9)
    at runQueue (eval at <anonymous> (http://localhost:8080/app.js:1318:2), <anonymous>:1264:3)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1318:2), <anonymous>:1341:5)

```

![screen shot 2016-11-18 at 5 06 28 pm](https://cloud.githubusercontent.com/assets/550518/20424535/61c5a028-adb1-11e6-951c-3c55ce8ca018.png)

**Comment by dylanninin** [comment]
```
# package.json
  ...
  "dependencies": {
    "es6-promise": "^4.0.5",
    "firebase": "^3.6.1",
    "vue": "^2.0.1",
    "vue-router": "^2.0.2",
    "vuex": "^2.0.0",
    "vuex-router-sync": "^2.1.1"
  }
  ...
```

```shell
# for vuex & vue-router >= 2.0:
npm install vuex-router-sync@next
```

And `"vuex-router-sync": "^2.1.1"` is upgraded to `"vuex-router-sync": "^3.0.0"`, restart npm, the issue is resolved.

Reference
- https://github.com/vuejs/vuex-router-sync
